In [7]:
import numpy as np

In [8]:
print('hello world')

hello world


In [9]:
my_list =[1,2,3]
my_list

[1, 2, 3]

In [10]:
np.array(my_list)

array([1, 2, 3])

In [11]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [12]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
my_list3 = [
    [[1,2,3],[4,5,6],[7,8,9]],
    [[10,11,12],[13,14,15],[16,17,18]],
    [[19,20,21],[22,23,24],[25,26,27]]
]

In [18]:
np.array(my_list3)

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [20]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [22]:
np.zeros(3)

array([0., 0., 0.])

In [23]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [24]:
np.ones(3)

array([1., 1., 1.])

In [25]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [26]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [27]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [28]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [29]:
np.random.rand(2)

array([0.90686533, 0.41771504])

In [30]:
np.random.rand(5,5)

array([[0.03102894, 0.46625201, 0.51520452, 0.83189496, 0.96523391],
       [0.5886148 , 0.90692833, 0.24066542, 0.56812195, 0.81492721],
       [0.55393654, 0.12165034, 0.94221003, 0.92503225, 0.02806823],
       [0.13878723, 0.61457642, 0.09077223, 0.50555306, 0.58865574],
       [0.79193114, 0.40723008, 0.33609576, 0.66356941, 0.92728568]])

In [31]:
np.random.randn(2)

array([0.61492908, 1.03810539])

In [33]:
np.random.randn(5,5)

array([[ 1.39378806, -0.97161263,  0.35283559, -1.467859  ,  0.97280911],
       [ 0.92556082,  1.17979742,  0.74733881,  0.16791618, -0.06985642],
       [-0.68886578,  0.76233635, -0.45255171,  0.67941359, -0.13126365],
       [-1.40320162, -0.36784701,  0.1464775 ,  0.68286351, -1.46491411],
       [-0.57050527, -1.73058026, -0.75994832,  0.14096178,  0.0306824 ]])

In [34]:
np.random.randint(1,100)

36

In [35]:
np.random.randint(1,100,10)

array([98, 82, 16, 75, 22, 71, 89, 20, 87, 61])

In [36]:
my_list = [1,2,3]
array_1d = np.array(my_list)

In [40]:
my_list2 = [[1,2,3],[4,5,3],[7,8,9]]
array_2d = np.array(my_list2)

In [41]:
array_3d = np.array(my_list3)

In [42]:
array_1d.shape

(3,)

In [43]:
array_2d.shape

(3, 3)

In [44]:
array_3d.shape

(3, 3, 3)

In [55]:
arr_list = ([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24])
arr = np.array(arr_list)

In [56]:
arr.shape

(25,)

In [57]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [58]:
arr.reshape(1,25).shape

(1, 25)

In [59]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [60]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [62]:
array_2d.reshape(-1)

array([1, 2, 3, 4, 5, 3, 7, 8, 9])

In [63]:
array_2d.reshape(-1).shape

(9,)

In [64]:
array_3d.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [65]:
array_3d.reshape(-1).shape

(27,)

In [69]:
ranarr_list = ([10, 12 ,41, 17, 49 ,2 ,46, 3 ,19, 39])
ranarr = np.array(ranarr_list)

In [70]:
ranarr.max()

49

In [71]:
ranarr.argmax()

4

In [72]:
ranarr.min()

2

In [73]:
ranarr.argmin()

5

In [74]:
arr.dtype

dtype('int32')

In [81]:
arr1=np.linspace(0,10,10)
arr1.dtype

dtype('float64')

In [82]:
arr2= np.arange(0,11)

In [83]:
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [84]:
arr2[8]

8

In [85]:
arr2[1:5]

array([1, 2, 3, 4])

In [90]:
arr2[0:5]

array([0, 1, 2, 3, 4])

In [89]:
arr2[0:10:2]

array([0, 2, 4, 6, 8])

In [92]:
arr2[0:5]=100

In [93]:
arr2

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [96]:
arr2 = np.arange(0,11)

In [97]:
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [105]:
slice_of_arr2 = arr2[0:6]

In [106]:
slice_of_arr2

array([0, 1, 2, 3, 4, 5])

In [107]:
slice_of_arr2[:]=99

In [108]:
slice_of_arr2

array([99, 99, 99, 99, 99, 99])

In [109]:
arr2

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [112]:
arr2_copy = arr2.copy()

In [113]:
arr2_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [115]:
arr_2d = np.array(([5,19,15],[20,25,30],[35,40,45]))

In [116]:
arr_2d

array([[ 5, 19, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [117]:
arr_2d[1]

array([20, 25, 30])

In [118]:
arr_2d[1][0]

20

In [119]:
arr_2d[1,0]

20

In [121]:
arr_2d[:2,1:]

array([[19, 15],
       [25, 30]])

In [122]:
arr_2d[:,2]

array([15, 30, 45])

In [126]:
arr3_list = ([0,1,2,3,4,5,6,7,8,9,10])
arr3 = np.array(arr3_list)

In [128]:
[arr3[2],arr3[5],arr3[9]]

[2, 5, 9]

In [129]:
arr3[[5,9,2]]

array([5, 9, 2])

In [131]:
arr_2d

array([[ 5, 19, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [132]:
arr_2d[[0,2]]

array([[ 5, 19, 15],
       [35, 40, 45]])

In [133]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [134]:
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [135]:
arr3 > 4

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [140]:
bool_arr3 = arr3>4

In [141]:
bool_arr3

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [142]:
arr3[bool_arr3]

array([ 5,  6,  7,  8,  9, 10])

In [143]:
arr3[arr3>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [144]:
x = 2
arr3[arr3>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])