In [3]:
import numpy as np

In [1]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [4]:
np.array(my_list)

array([1, 2, 3])

In [5]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
my_list3 = [
    [[1,2,3],[4,5,6],[7,8,9]],
    [[10,11,12],[13,14,15],[16,17,18]],
    [[19,20,21],[22,23,24],[25,26,27]]
]

In [8]:
np.array(my_list3)

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [9]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [11]:
np.zeros(3)

array([0., 0., 0.])

In [12]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.ones(3)

array([1., 1., 1.])

In [14]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [16]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [18]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [19]:
np.random.rand(2)

array([0.51548155, 0.79875486])

In [20]:
np.random.rand(5,5)

array([[0.82737441, 0.86155807, 0.47167135, 0.30681739, 0.2278664 ],
       [0.89217903, 0.98091581, 0.06536052, 0.40806453, 0.76029529],
       [0.98689539, 0.02468643, 0.47552275, 0.65059855, 0.98149374],
       [0.89512153, 0.04741227, 0.31504034, 0.62536087, 0.81359814],
       [0.77813723, 0.0987503 , 0.51080711, 0.93177681, 0.35342068]])

In [21]:
np.random.rand(2)

array([0.73424285, 0.57059638])

In [22]:
np.random.randn(5,5)

array([[ 0.54978399,  0.87463539, -0.31386435, -0.09515256, -2.37232296],
       [ 0.71686147,  0.45014006,  1.83587183,  1.05625138,  1.27828152],
       [ 0.37921179,  1.77762276, -0.39481384, -1.47250833, -0.25558435],
       [-0.36034617,  0.28212319,  0.65113699,  0.12659289, -0.58598215],
       [-0.65691816, -0.1685333 ,  0.1535731 , -0.99442009,  0.40434105]])

In [23]:
np.random.randint(1,100)

49

In [24]:
np.random.randint(1,100,10)

array([98, 77, 62, 13, 48, 30, 35, 18, 94, 66])

In [33]:
my_list
array_1d = np.array(my_list)

In [28]:
my_list2 = [[1,2,3],[4,5,3],[7,8,9]]
array_2d = np.array(my_list2)

In [29]:
array_3d = np.array(my_list3)

In [34]:
array_1d.shape

(3,)

In [35]:
array_2d.shape

(3, 3)

In [36]:
array_3d.shape

(3, 3, 3)

In [42]:
arr_list = [0,1,2,3,4,5,3,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24]
arr = np.array(arr_list)

In [43]:
arr.shape

(25,)

In [44]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  3,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [45]:
arr.reshape(1,25).shape

(1, 25)

In [46]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  3,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [47]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 3],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [48]:
array_2d.reshape(-1)

array([1, 2, 3, 4, 5, 3, 7, 8, 9])

In [49]:
array_2d.reshape(-1).shape

(9,)

In [50]:
array_3d.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [51]:
array_3d.reshape(-1).shape

(27,)

In [63]:
ranarr_list = [10,12,41,17,49,2,46,3,19,39]
ranarr = np.array(ranarr_list)

In [64]:
ranarr.max()

49

In [65]:
ranarr.argmax()


4

In [66]:
ranarr.min()


2

In [67]:
ranarr.argmin()

5

In [68]:
arr.dtype

dtype('int32')

In [69]:
arr1=np.linspace(0,10,10)
arr1.dtype

dtype('float64')

In [70]:
arr= np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [72]:
arr[8]


8

In [73]:
arr[1:5]


array([1, 2, 3, 4])

In [74]:
arr[0:5]


array([0, 1, 2, 3, 4])

In [75]:
arr[0:10:2]

array([0, 2, 4, 6, 8])

In [78]:
arr[0:5]=100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [79]:
arr = np.arange(0,11)

In [80]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [81]:
slice_of_arr = arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [82]:
slice_of_arr[:]=99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [83]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [84]:
arr_copy  = arr.copy()
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [85]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [86]:
arr_2d[1]

array([20, 25, 30])

In [87]:
arr_2d[1][0]

20

In [88]:
arr_2d[1,0]

20

In [89]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [90]:
arr_2d[:,2]

array([15, 30, 45])

In [91]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [94]:
arr[0:6] = [0,1,2,3,4,5]

In [95]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [96]:
[arr[2],arr[5],arr[9]]

[2, 5, 9]

In [97]:
arr[[2,5,9]]

array([2, 5, 9])

In [98]:
arr[[5,9,2]]

array([5, 9, 2])

In [99]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

In [100]:
arr_2d[[0,2]]

array([[ 5, 10, 15],
       [35, 40, 45]])

In [101]:
arr = np.arange(1,11)

In [102]:
arr > 7

array([False, False, False, False, False, False, False,  True,  True,
        True])

In [103]:
bool_arr = arr > 2*2

In [104]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [105]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [106]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [107]:
x= 2*3/2
arr[arr>x]

array([ 4,  5,  6,  7,  8,  9, 10])